### ISSUE TITLE
結果入力で、TAB でも良い感じに確定されてほしい

### ISSUE THREAD

**Issue by emaame** [suitougreentea/the-masters-scripts#2]
1. 結果入力のテキストボックスで、Enter ではなく、TAB でも確定できると嬉しいです。
2. あわよくば、Shift+TAB/Enter が手前にフォーカス移動とか？

優先度は低いと思います。

**Comment by emaame** [comment]
#1 とともに、練習で自分で触ってみたさはあります

**Comment by suitougreentea** [comment]
#1 とあわせて返答します。
・Tab/Shift+Tabでフォーカスが移動するようにすでになっている（はずな）ので、そのタイミングで確定が起こるはずです。
・Enterでもフォーカス移動ができると良い感じでしょうか。ボタンまでフォーカスが移動した状態でEnter押すと確定、みたいな。

現在システムがスプレッドシートから公開されているApps Scriptに依存しているので、多人数での開発作業に向いていない状況です。おいおいローカルでも動作が完結できるようにApps Script部分のローカル版を作りたいなあと思っています。

**Comment by suitougreentea** [comment]
Enterキーフォーカス移動対応しました。
#15 は未解決なのでそちらで。
