### ISSUE TITLE
走者向けタイマー表示の拡大表示

### ISSUE THREAD

**Issue by emaame** [suitougreentea/the-masters-scripts#3]
離れた位置の走者がタイマーを自身で確認できない

## 解決案

全員開始まで、タイマーをくそデカ表示させたいです。

1. タイマーが動いている間、タイマー部分が拡大レイアウトされる
2. （一案として）対応画面上にカウントダウンがでる（絵がうるさい？）

## 代替案

現状、ブラウザのズームで運用可

**Comment by emaame** [comment]
結果入力ダイアログも画面全体ぐらいに大きくなると老眼に優しくて嬉しいです

**Comment by suitougreentea** [comment]
やりたいですね！（本番のとき思ったより小さかった・・・）

**Comment by suitougreentea** [comment]
解像度を1280x720と想定してデザインしなおしました（先月は1920x1080）。全パーツが大きくなるので見やすくなるかと思います。
