### ISSUE TITLE
Twitter 向けテキストのフォーマット

### ISSUE THREAD

**Issue by emaame** [suitougreentea/the-masters-scripts#4]
## 提案
 
結果の確定後に表示されるリンクが Twitter 投稿向けにフォーマットされていても良いのではと思いました。

'''
The Masters {Nth} の結果です。

{URL}
'''

過去の分を探してコピベされていたので、楽かなと。次回予告のテンプレも入れておいて良いのかもです。

## also

[Clipboard API](https://developer.mozilla.org/ja/docs/Web/API/Clipboard_API) でクリップボードにコピー済みだと楽そうでした。権限とかの問題が無ければ。
（一開催で一回しか使わないですが）

**Comment by suitougreentea** [comment]
[Tweet Button](https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview)を検討してます！

**Comment by suitougreentea** [comment]
エクスポート後にツイートするか聞くようにしました。
